# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a797dcbba2b9f30eac946ade6b5ace9058c856f282dd76630f73949490ea5bcd76fe7f60c36dd492334e55f437a6a4e31b3ebef29e8b9851a8bb4dad0fddeec7

test:
  secret_key_base: 2133291f7eb55f1cb6ca2f1c818274a60ca95c7566baa642200e7476795c7a52177e623e92863c10fe061fe8d549b6d763158d01c516e72025c71c9afd7aae5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
